window.phoneRadarDaily = {
  "updatedAt": "2026-07-05T15:37:45.238Z",
  "issueDate": "2026-07-05",
  "issue": "VOL.260705",
  "title": "手机情报日报",
  "intro": "今日筛出 19 条重点，其中 8 条是重点爆料，包含 8 条 iPhone 相关、1 条官方确认、0 条参数线索。",
  "stats": {
    "total": 19,
    "iphone": 8,
    "leaks": 8,
    "official": 1,
    "specs": 0
  },
  "sections": [
    {
      "id": "leaks",
      "title": "重点爆料",
      "hint": "机模、配色、影像、屏幕、电池和芯片线索先看。",
      "items": [
        {
          "id": "auto-eabc94dc6d73",
          "title": "郭明錤称苹果折叠屏手机可能重演 iPhone X 剧本：同场发布、较晚开卖，供应紧张延续至年底",
          "originalTitle": "",
          "source": "IT之家",
          "brand": "iPhone",
          "type": "爆料",
          "trust": "媒体汇总",
          "date": "2026-07-05",
          "time": "14:37",
          "publishedAt": "2026-07-05T14:37:24.000Z",
          "url": "https://www.ithome.com/0/972/859.htm",
          "image": "https://img.ithome.com/newsuploadfiles/2026/7/a600f6b1-0535-48e3-8825-83aa8a22bfed.jpg",
          "verdict": "先看",
          "takeaway": "IT之家 7 月 5 日消息，天风国际证券分析师郭明錤今晚在 X 平台发文，称折叠 iPhone 可能重演 iPhone X 剧本： 同场发布、延后开售，供应吃紧延续至年底 。 据其最新产业调查，折叠 iPhone 在 2H26（2026 年下半年）的组装出货量约 700‒800 万部，其中 3Q26（2026 年第三季度）出货量为 50‒100 万部（占…",
          "detail": "IT之家 7 月 5 日消息，天风国际证券分析师郭明錤今晚在 X 平台发文，称折叠 iPhone 可能重演 iPhone X 剧本： 同场发布、延后开售，供应吃紧延续至年底 。 据其最新产业调查，折叠 iPhone 在 2H26（2026 年下半年）的组装出货量约 700‒800 万部，其中 3Q26（2026 年第三季度）出货量为 50‒100 万部（占…",
          "keyPoints": [
            "屏幕形态"
          ],
          "confidence": "媒体汇总或普通传闻，适合先收藏观察，不当作最终参数。",
          "impact": "这是提前爆料，能决定你要不要继续等某款机型，但还要交叉验证。",
          "action": "先收藏到重点爆料；等第二个可靠来源、认证或发布会再确认。"
        },
        {
          "id": "coolapk-user-93fd53f87274",
          "title": "JSCHEN小小狐：博主分析 iPhone 18 Pro 系列电池入网信息",
          "originalTitle": "",
          "source": "JSCHEN小小狐",
          "brand": "iPhone",
          "type": "爆料",
          "trust": "高可信爆料",
          "date": "2026-07-04",
          "time": "01:26",
          "publishedAt": "2026-07-04T01:26:30.000Z",
          "url": "https://www.coolapk.com/feed/72640797",
          "image": "http://image.coolapk.com/feed/2026/0704/09/4702274_4087c09c_8389_1222_271@1725x1927.jpg",
          "verdict": "先看",
          "takeaway": "『博主分析 iPhone 18 Pro 系列电池入网信息』 知名数码博主 数码闲聊站 发博表示，根据苹果电池供应商最新 3C 入网信息推测，iPhone 18 Pro 系列国行及美版电池或为以下规格： iPhone 18 Pro 国行 4056mAh / 美版 4288mAh iPhone 18 Pro Max 国行 5391mAh / 美版 5567mA…",
          "detail": "『博主分析 iPhone 18 Pro 系列电池入网信息』 知名数码博主 数码闲聊站 发博表示，根据苹果电池供应商最新 3C 入网信息推测，iPhone 18 Pro 系列国行及美版电池或为以下规格： iPhone 18 Pro 国行 4056mAh / 美版 4288mAh iPhone 18 Pro Max 国行 5391mAh / 美版 5567mA…",
          "keyPoints": [
            "电池 / 充电",
            "爆料来源"
          ],
          "confidence": "来自常见高关注爆料源，适合重点看，但仍需等第二来源或发布会确认。",
          "impact": "这是提前爆料，能决定你要不要继续等某款机型，但还要交叉验证。",
          "action": "先收藏到重点爆料；等第二个可靠来源、认证或发布会再确认。"
        },
        {
          "id": "auto-9a5f3ea4a833",
          "title": "消息称 HMD Skyline 2 手机仍将发布：相机模组设计与初代相同、搭骁龙 7s Gen 4 处理器",
          "originalTitle": "",
          "source": "IT之家",
          "brand": "行业",
          "type": "爆料",
          "trust": "媒体汇总",
          "date": "2026-07-05",
          "time": "13:02",
          "publishedAt": "2026-07-05T13:02:09.000Z",
          "url": "https://www.ithome.com/0/972/840.htm",
          "image": "https://img.ithome.com/newsuploadfiles/2026/7/8ce6e7ae-0217-48fe-a2cc-cf7159a0d028.jpg?x-bce-process=image/format,f_auto",
          "verdict": "先看",
          "takeaway": "IT之家 7 月 5 日消息，消息源 smashx_60 发文，确认先前 HMD Skyline 2“被砍”消息系误解，只是 砍掉了其中的 GT 机型 ，标准版机型仍将发布。 消息源同步更新了该机最新工程机的规格信息和背部相机模组谍照，相对于去年 5 月曝光的配置主要将 SoC 从骁龙 7s Gen 3 换成 7s Gen 4，其他规格不变。 具体来看，该…",
          "detail": "IT之家 7 月 5 日消息，消息源 smashx_60 发文，确认先前 HMD Skyline 2“被砍”消息系误解，只是 砍掉了其中的 GT 机型 ，标准版机型仍将发布。 消息源同步更新了该机最新工程机的规格信息和背部相机模组谍照，相对于去年 5 月曝光的配置主要将 SoC 从骁龙 7s Gen 3 换成 7s Gen 4，其他规格不变。 具体来看，该…",
          "keyPoints": [
            "外观 / 配色 / 尺寸",
            "影像硬件",
            "芯片 / 性能",
            "爆料来源"
          ],
          "confidence": "媒体汇总或普通传闻，适合先收藏观察，不当作最终参数。",
          "impact": "这是提前爆料，能决定你要不要继续等某款机型，但还要交叉验证。",
          "action": "先收藏到重点爆料；等第二个可靠来源、认证或发布会再确认。"
        },
        {
          "id": "newsnow-7816e1d408bc",
          "title": "K90至尊就是目前最流畅的澎湃，最流畅的米系手机，彻底解决了K90 Pro Max和小米17全系列日用极其容易发烫，发烫后掉帧卡顿的问题，主动散热就是力大飞砖，这流畅度在米系机型里面确实是登顶了，跟天玑9500的K90 max相比，至尊更流畅，max续航更好。",
          "originalTitle": "",
          "source": "酷安热榜",
          "brand": "Xiaomi",
          "type": "爆料",
          "trust": "高关注爆料源",
          "date": "2026-07-05",
          "time": "",
          "publishedAt": "",
          "url": "https://www.coolapk.com/feed/72647704",
          "image": "",
          "verdict": "先看",
          "takeaway": "K90至尊就是目前最流畅的澎湃，最流畅的米系手机，彻底解决了K90 Pro Max和小米17全系列日用极其容易发烫，发烫后掉帧卡顿的问题，主动散热就是力大飞砖，这流畅度在米系机型里面确实是登顶了，跟天玑9500的K90 max相比，至尊更流畅，max续航更好。",
          "detail": "K90至尊就是目前最流畅的澎湃，最流畅的米系手机，彻底解决了K90 Pro Max和小米17全系列日用极其容易发烫，发烫后掉帧卡顿的问题，主动散热就是力大飞砖，这流畅度在米系机型里面确实是登顶了，跟天玑9500的K90 max相比，至尊更流畅，max续航更好。",
          "keyPoints": [
            "电池 / 充电"
          ],
          "confidence": "媒体汇总或普通传闻，适合先收藏观察，不当作最终参数。",
          "impact": "这是提前爆料，能决定你要不要继续等某款机型，但还要交叉验证。",
          "action": "先收藏到重点爆料；等第二个可靠来源、认证或发布会再确认。"
        },
        {
          "id": "coolapk-user-901cd9637d15",
          "title": "竹本青：除了续航不行，其他都挺好使",
          "originalTitle": "",
          "source": "竹本青",
          "brand": "OPPO",
          "type": "爆料",
          "trust": "高可信爆料",
          "date": "2026-07-05",
          "time": "14:24",
          "publishedAt": "2026-07-05T14:24:17.000Z",
          "url": "https://www.coolapk.com/feed/72663388",
          "image": "",
          "verdict": "先看",
          "takeaway": "除了续航不行，其他都挺好使",
          "detail": "除了续航不行，其他都挺好使",
          "keyPoints": [
            "电池 / 充电"
          ],
          "confidence": "可信度较高，但仍属于发布前线索。",
          "impact": "这是提前爆料，能决定你要不要继续等某款机型，但还要交叉验证。",
          "action": "先收藏到重点爆料；等第二个可靠来源、认证或发布会再确认。"
        },
        {
          "id": "coolapk-user-ee2a51c5b808",
          "title": "竹本青：【vivo X300E 详细配置曝光：1.5K中直屏，骁龙8 Gen5，中底潜望镜】 ▫️6.59\"1.5K OL…",
          "originalTitle": "",
          "source": "竹本青",
          "brand": "vivo",
          "type": "爆料",
          "trust": "高可信爆料",
          "date": "2026-07-04",
          "time": "13:21",
          "publishedAt": "2026-07-04T13:21:47.000Z",
          "url": "https://www.coolapk.com/feed/72649471",
          "image": "http://image.coolapk.com/feed/2026/0704/21/4248714_1b950b6e_1305_894_255@1270x751.jpg",
          "verdict": "先看",
          "takeaway": "【vivo X300E 详细配置曝光：1.5K中直屏，骁龙8 Gen5，中底潜望镜】 ▫️6.59\"1.5K OLED直屏 ▫️骁龙8 Gen5处理器 ▫️7100mAh±电池+90W有线 前置｜50Mp 主摄｜50Mp 大底主摄 潜望｜50Mp IMX8中底 超广｜8Mp ▫️后置左上小方块Deco ▫️或配备金属中框、超声波指纹 ▫️厚7.99mm/重…",
          "detail": "【vivo X300E 详细配置曝光：1.5K中直屏，骁龙8 Gen5，中底潜望镜】 ▫️6.59\"1.5K OLED直屏 ▫️骁龙8 Gen5处理器 ▫️7100mAh±电池+90W有线 前置｜50Mp 主摄｜50Mp 大底主摄 潜望｜50Mp IMX8中底 超广｜8Mp ▫️后置左上小方块Deco ▫️或配备金属中框、超声波指纹 ▫️厚7.99mm/重…",
          "keyPoints": [
            "影像硬件",
            "屏幕形态",
            "电池 / 充电",
            "芯片 / 性能"
          ],
          "confidence": "可信度较高，但仍属于发布前线索。",
          "impact": "这是提前爆料，能决定你要不要继续等某款机型，但还要交叉验证。",
          "action": "先收藏到重点爆料；等第二个可靠来源、认证或发布会再确认。"
        },
        {
          "id": "coolapk-user-35adf37c0137",
          "title": "JSCHEN小小狐：博主汇总 vivo X300E 详细参数：骁龙8 Gen5",
          "originalTitle": "",
          "source": "JSCHEN小小狐",
          "brand": "vivo",
          "type": "爆料",
          "trust": "高可信爆料",
          "date": "2026-07-04",
          "time": "06:20",
          "publishedAt": "2026-07-04T06:20:38.000Z",
          "url": "https://www.coolapk.com/feed/72644401",
          "image": "http://image.coolapk.com/feed/2026/0704/14/4702274_f5d8f8ae_6036_8609_522@1440x833.jpg",
          "verdict": "先看",
          "takeaway": "『博主汇总 vivo X300E 详细参数: 骁龙8 Gen5』 ◇ 6.59 英寸 1.5K LTPS OLED 直屏 ◇ 骁龙 8 Gen5 移动平台 ◇ 50Mp 1/1.56'' 大底主摄 ◇ 50Mp 1/1.95'' IMX8 中底潜望 ◇ 8Mp 超广角 + 前置 50Mp，蔡司影像 ◇ 7015mAh/7100mAh± 电池，90W 快充…",
          "detail": "『博主汇总 vivo X300E 详细参数: 骁龙8 Gen5』 ◇ 6.59 英寸 1.5K LTPS OLED 直屏 ◇ 骁龙 8 Gen5 移动平台 ◇ 50Mp 1/1.56'' 大底主摄 ◇ 50Mp 1/1.95'' IMX8 中底潜望 ◇ 8Mp 超广角 + 前置 50Mp，蔡司影像 ◇ 7015mAh/7100mAh± 电池，90W 快充…",
          "keyPoints": [
            "影像硬件",
            "屏幕形态",
            "电池 / 充电"
          ],
          "confidence": "可信度较高，但仍属于发布前线索。",
          "impact": "这是提前爆料，能决定你要不要继续等某款机型，但还要交叉验证。",
          "action": "先收藏到重点爆料；等第二个可靠来源、认证或发布会再确认。"
        },
        {
          "id": "coolapk-user-847489662e28",
          "title": "竹本青：OPPO被指红包雨“砍奖”：中奖者称7次中奖仅给1个奖品",
          "originalTitle": "",
          "source": "竹本青",
          "brand": "OPPO",
          "type": "爆料",
          "trust": "高可信爆料",
          "date": "2026-07-05",
          "time": "10:14",
          "publishedAt": "2026-07-05T10:14:49.000Z",
          "url": "https://www.coolapk.com/feed/72660300",
          "image": "http://image.coolapk.com/feed/2026/0705/18/4248714_dc444a35_6487_7945_866@550x397.jpg",
          "verdict": "先看",
          "takeaway": "【OPPO被指红包雨“砍奖”，中奖者称7次中奖仅给1个奖品】 据新浪科技《BUG》栏目今日报道，近日，OPPO又因6·18大促期间的红包雨奖品发放事宜，触怒了多数获奖人。 事因OPPO公布了红包名单。但该名单最新规定同一用户获得多份奖品仅发放“价值最高”的一件的做法，很快引发了大量获奖人的不满。 据多位获奖人对《BUG》栏目透露，自己在该红包雨活动期间，连…",
          "detail": "【OPPO被指红包雨“砍奖”，中奖者称7次中奖仅给1个奖品】 据新浪科技《BUG》栏目今日报道，近日，OPPO又因6·18大促期间的红包雨奖品发放事宜，触怒了多数获奖人。 事因OPPO公布了红包名单。但该名单最新规定同一用户获得多份奖品仅发放“价值最高”的一件的做法，很快引发了大量获奖人的不满。 据多位获奖人对《BUG》栏目透露，自己在该红包雨活动期间，连…",
          "keyPoints": [
            "爆料"
          ],
          "confidence": "可信度较高，但仍属于发布前线索。",
          "impact": "这是提前爆料，能决定你要不要继续等某款机型，但还要交叉验证。",
          "action": "先收藏到重点爆料；等第二个可靠来源、认证或发布会再确认。"
        }
      ]
    },
    {
      "id": "iphone",
      "title": "iPhone 重点",
      "hint": "不是硬件爆料，但和 iPhone 体验或路线有关。",
      "items": [
        {
          "id": "newsnow-762a674dbc9a",
          "title": "曝 iPhone 18 Pro 1TB / 2TB 版本采用 QLC 闪存颗粒",
          "originalTitle": "",
          "source": "酷安热榜",
          "brand": "iPhone",
          "type": "爆料",
          "trust": "高关注爆料源",
          "date": "2026-07-05",
          "time": "",
          "publishedAt": "",
          "url": "https://www.coolapk.com/feed/72648889",
          "image": "",
          "verdict": "先看",
          "takeaway": "曝 iPhone 18 Pro 1TB / 2TB 版本采用 QLC 闪存颗粒",
          "detail": "曝 iPhone 18 Pro 1TB / 2TB 版本采用 QLC 闪存颗粒",
          "keyPoints": [
            "爆料"
          ],
          "confidence": "媒体汇总或普通传闻，适合先收藏观察，不当作最终参数。",
          "impact": "当作提前信号，别急着下结论，等第二个来源验证。",
          "action": "英文源先别打开，除非你要我帮你翻译/判断。"
        },
        {
          "id": "auto-9bbf43c61c96",
          "title": "iPhone 系统功能 / AI 体验相关消息",
          "originalTitle": "",
          "source": "Apple Newsroom",
          "brand": "iPhone",
          "type": "官方",
          "trust": "官方确认",
          "date": "2026-07-05",
          "time": "",
          "publishedAt": "",
          "url": "https://www.apple.com/newsroom/2026/06/apple-announces-changes-to-ios-in-brazil/",
          "image": "",
          "verdict": "先看",
          "takeaway": "iPhone 系统功能 / AI 体验相关消息。已转成中文摘要展示，详细内容可打开原文核对。",
          "detail": "iPhone 系统功能 / AI 体验相关消息。这条来自英文来源，已先转成中文结论；需要更细节时再打开原文核对。",
          "keyPoints": [
            "官方"
          ],
          "confidence": "官方内容，可直接作为已确认信息记录。",
          "impact": "可信度高，但如果不是配置/价格消息，只需要扫一眼。",
          "action": "英文源先别打开，除非你要我帮你翻译/判断。"
        },
        {
          "id": "coolapk-user-1db37419eeb5",
          "title": "竹本青：iPhone 17系列中国区最新销量曝光：已超3630万台",
          "originalTitle": "",
          "source": "竹本青",
          "brand": "iPhone",
          "type": "爆料",
          "trust": "高可信爆料",
          "date": "2026-07-04",
          "time": "12:09",
          "publishedAt": "2026-07-04T12:09:37.000Z",
          "url": "https://www.coolapk.com/feed/72648594",
          "image": "http://image.coolapk.com/feed/2026/0704/20/4248714_9c1723af_6977_0042_71@2160x1666.jpg",
          "verdict": "先看",
          "takeaway": "【iPhone 17系列 中国区最新销量曝光：已超3630万台】 7月4日，博主「RD观测」发布第三方统计数据：截至2026年第26周，iPhone 17系列在中国市场累计销量约3630.44万台。 前几周数据如下： 截至2026 W25 —— 约3538.55万 截至2026 W24 —— 约3433.98万 截至2026 W23 —— 约3320.36…",
          "detail": "【iPhone 17系列 中国区最新销量曝光：已超3630万台】 7月4日，博主「RD观测」发布第三方统计数据：截至2026年第26周，iPhone 17系列在中国市场累计销量约3630.44万台。 前几周数据如下： 截至2026 W25 —— 约3538.55万 截至2026 W24 —— 约3433.98万 截至2026 W23 —— 约3320.36…",
          "keyPoints": [
            "爆料"
          ],
          "confidence": "可信度较高，但仍属于发布前线索。",
          "impact": "当作提前信号，别急着下结论，等第二个来源验证。",
          "action": "英文源先别打开，除非你要我帮你翻译/判断。"
        },
        {
          "id": "newsnow-ff053d70e8f3",
          "title": "印度工厂泄露 iPhone18Pro 机密，这如何影响苹果在印度的布局？",
          "originalTitle": "",
          "source": "知乎热榜",
          "brand": "iPhone",
          "type": "市场报告",
          "trust": "媒体汇总",
          "date": "2026-07-05",
          "time": "",
          "publishedAt": "",
          "url": "https://www.zhihu.com/question/2056716909140354522",
          "image": "",
          "verdict": "扫一眼",
          "takeaway": "印度工厂泄露 iPhone18Pro 机密，这如何影响苹果在印度的布局？",
          "detail": "印度工厂泄露 iPhone18Pro 机密，这如何影响苹果在印度的布局？",
          "keyPoints": [
            "市场报告"
          ],
          "confidence": "媒体汇总或普通传闻，适合先收藏观察，不当作最终参数。",
          "impact": "目前更像背景信息，对买手机影响不大。",
          "action": "英文源先别打开，除非你要我帮你翻译/判断。"
        },
        {
          "id": "auto-f9464a78a381",
          "title": "iPhone 相关消息",
          "originalTitle": "",
          "source": "9to5Mac",
          "brand": "iPhone",
          "type": "爆料",
          "trust": "媒体汇总",
          "date": "2026-07-05",
          "time": "03:07",
          "publishedAt": "2026-07-05T03:07:08.000Z",
          "url": "https://9to5mac.com/2026/07/04/iphone-17-pro-max-included-in-america-250-time-capsule/",
          "image": "https://9to5mac.com/wp-content/uploads/sites/6/2025/10/iphone-17-pro-cosmic-orange-fernando.jpg?quality=82&strip=all&w=1600",
          "verdict": "扫一眼",
          "takeaway": "iPhone 相关消息。已转成中文摘要展示，详细内容可打开原文核对。",
          "detail": "iPhone 相关消息。这条来自英文来源，已先转成中文结论；需要更细节时再打开原文核对。",
          "keyPoints": [
            "爆料"
          ],
          "confidence": "媒体汇总或普通传闻，适合先收藏观察，不当作最终参数。",
          "impact": "当作提前信号，别急着下结论，等第二个来源验证。",
          "action": "英文源先别打开，除非你要我帮你翻译/判断。"
        },
        {
          "id": "auto-2adbc3d85daf",
          "title": "iPhone 18 Pro 电池 / 充电相关消息",
          "originalTitle": "",
          "source": "Gizmochina",
          "brand": "iPhone",
          "type": "爆料",
          "trust": "媒体汇总",
          "date": "2026-07-04",
          "time": "04:21",
          "publishedAt": "2026-07-04T04:21:00.000Z",
          "url": "https://www.gizmochina.com/2026/07/04/iphone-18-pro-and-pro-max-battery-capacities-confirmed-via-3c-certification/",
          "image": "https://www.gizmochina.com/wp-content/uploads/2026/02/iPhone-18-Pro-Deep-Red-Feature_l_large-300x168.jpg?x44794",
          "verdict": "扫一眼",
          "takeaway": "iPhone 18 Pro 电池 / 充电相关消息。已转成中文摘要展示，详细内容可打开原文核对。",
          "detail": "iPhone 18 Pro 电池 / 充电相关消息。这条来自英文来源，已先转成中文结论；需要更细节时再打开原文核对。",
          "keyPoints": [
            "电池 / 充电"
          ],
          "confidence": "媒体汇总或普通传闻，适合先收藏观察，不当作最终参数。",
          "impact": "影响日常体验，尤其是游戏、拍照和长时间使用。",
          "action": "有具体参数就记录到参数库；没有参数就先收藏。"
        }
      ]
    },
    {
      "id": "market",
      "title": "行业趋势",
      "hint": "看方向，不急着当购买依据。",
      "items": [
        {
          "id": "newsnow-539e7c5ecc69",
          "title": "自从玩酷安后，换手机的频率越来越高[流泪]本质上还是自己的消费习惯，我要改变，从k90至尊开始#REDMIK90至尊版# #HyperOS3# #数码日常#",
          "originalTitle": "",
          "source": "酷安热榜",
          "brand": "Xiaomi",
          "type": "爆料",
          "trust": "高关注爆料源",
          "date": "2026-07-05",
          "time": "",
          "publishedAt": "",
          "url": "https://www.coolapk.com/feed/72640972",
          "image": "",
          "verdict": "先看",
          "takeaway": "自从玩酷安后，换手机的频率越来越高[流泪]本质上还是自己的消费习惯，我要改变，从k90至尊开始#REDMIK90至尊版# #HyperOS3# #数码日常#",
          "detail": "自从玩酷安后，换手机的频率越来越高[流泪]本质上还是自己的消费习惯，我要改变，从k90至尊开始#REDMIK90至尊版# #HyperOS3# #数码日常#",
          "keyPoints": [
            "爆料"
          ],
          "confidence": "媒体汇总或普通传闻，适合先收藏观察，不当作最终参数。",
          "impact": "当作提前信号，别急着下结论，等第二个来源验证。",
          "action": "英文源先别打开，除非你要我帮你翻译/判断。"
        },
        {
          "id": "coolapk-user-7a011460bb99",
          "title": "JSCHEN小小狐：跑了趟嘉兴，结果出发时没带伞 下车被雨浇了个透…… #手机摄影#",
          "originalTitle": "",
          "source": "JSCHEN小小狐",
          "brand": "Xiaomi",
          "type": "爆料",
          "trust": "高可信爆料",
          "date": "2026-07-04",
          "time": "01:46",
          "publishedAt": "2026-07-04T01:46:45.000Z",
          "url": "https://www.coolapk.com/feed/72641013",
          "image": "http://image.coolapk.com/feed/2026/0704/09/4702274_335f29bf_9601_6838_283-uhdr@2365x3504.jpg",
          "verdict": "扫一眼",
          "takeaway": "跑了趟嘉兴，结果出发时没带伞 下车被雨浇了个透…… #手机摄影#",
          "detail": "跑了趟嘉兴，结果出发时没带伞 下车被雨浇了个透…… #手机摄影#",
          "keyPoints": [
            "爆料"
          ],
          "confidence": "可信度较高，但仍属于发布前线索。",
          "impact": "当作提前信号，别急着下结论，等第二个来源验证。",
          "action": "英文源先别打开，除非你要我帮你翻译/判断。"
        },
        {
          "id": "newsnow-be42cbceba58",
          "title": "REDMI K90 Max \"地漏\"",
          "originalTitle": "",
          "source": "酷安热榜",
          "brand": "Xiaomi",
          "type": "爆料",
          "trust": "高关注爆料源",
          "date": "2026-07-05",
          "time": "",
          "publishedAt": "",
          "url": "https://www.coolapk.com/feed/72639262",
          "image": "",
          "verdict": "扫一眼",
          "takeaway": "REDMI K90 Max \"地漏\"",
          "detail": "REDMI K90 Max \"地漏\"",
          "keyPoints": [
            "爆料"
          ],
          "confidence": "媒体汇总或普通传闻，适合先收藏观察，不当作最终参数。",
          "impact": "当作提前信号，别急着下结论，等第二个来源验证。",
          "action": "英文源先别打开，除非你要我帮你翻译/判断。"
        },
        {
          "id": "coolapk-user-a1be14efe241",
          "title": "竹本青：【小米 17系列 最新总销量曝光：全系超554万，Ultra近23.1万】 小米 17系列 截至2026 W26…",
          "originalTitle": "",
          "source": "竹本青",
          "brand": "Xiaomi",
          "type": "爆料",
          "trust": "高可信爆料",
          "date": "2026-07-05",
          "time": "13:22",
          "publishedAt": "2026-07-05T13:22:55.000Z",
          "url": "https://www.coolapk.com/feed/72662542",
          "image": "http://image.coolapk.com/feed/2026/0705/21/4248714_b0c3da23_7774_0889_327@2930x2829.jpg",
          "verdict": "扫一眼",
          "takeaway": "【小米 17系列 最新总销量曝光：全系超554万，Ultra近23.1万】 小米 17系列 截至2026 W26 —— 约554.01万 截至2026 W25 —— 约544.96万 截至2026 W24 —— 约531.72万 截至2026 W23 —— 约517.2万 小米 17 Ultra 截至2026 W26 —— 约23.07万 截至2026 W…",
          "detail": "【小米 17系列 最新总销量曝光：全系超554万，Ultra近23.1万】 小米 17系列 截至2026 W26 —— 约554.01万 截至2026 W25 —— 约544.96万 截至2026 W24 —— 约531.72万 截至2026 W23 —— 约517.2万 小米 17 Ultra 截至2026 W26 —— 约23.07万 截至2026 W…",
          "keyPoints": [
            "爆料"
          ],
          "confidence": "可信度较高，但仍属于发布前线索。",
          "impact": "当作提前信号，别急着下结论，等第二个来源验证。",
          "action": "英文源先别打开，除非你要我帮你翻译/判断。"
        },
        {
          "id": "auto-a75e188c9856",
          "title": "Vivo X300 Pro 对比 Vivo X300 Ultra：差异整理",
          "originalTitle": "",
          "source": "Gizmochina",
          "brand": "vivo",
          "type": "爆料",
          "trust": "媒体汇总",
          "date": "2026-07-05",
          "time": "13:05",
          "publishedAt": "2026-07-05T13:05:47.000Z",
          "url": "https://www.gizmochina.com/2026/07/05/vivo-x300-pro-vs-vivo-x300-ultra-is-the-ultra-worth-the-extra-500/",
          "image": "https://www.gizmochina.com/wp-content/uploads/2026/07/image-25-300x176.png?x44794",
          "verdict": "可略过",
          "takeaway": "Vivo X300 Pro 对比 Vivo X300 Ultra：重点看定位、配置差异和价格差，判断是否值得等更高端型号。",
          "detail": "Vivo X300 Pro 对比 Vivo X300 Ultra 的差异整理。重点看两款机型的定位、影像规格、屏幕尺寸、价格区间和发布时间是否拉开差距。",
          "keyPoints": [
            "成本 / 价格"
          ],
          "confidence": "媒体汇总或普通传闻，适合先收藏观察，不当作最终参数。",
          "impact": "影响购买预算，值得先看。",
          "action": "有具体参数就记录到参数库；没有参数就先收藏。"
        }
      ]
    }
  ]
};
