window.phoneRadarDaily = {
  "updatedAt": "2026-10-05T09:02:13.476Z",
  "issueDate": "2026-10-05",
  "issue": "VOL.261005",
  "title": "手机情报日报",
  "intro": "今日筛出 20 条重点，其中 8 条是重点爆料，包含 9 条 iPhone 相关、3 条官方确认、0 条参数线索。",
  "stats": {
    "total": 20,
    "iphone": 9,
    "leaks": 8,
    "official": 3,
    "specs": 0
  },
  "sections": [
    {
      "id": "leaks",
      "title": "重点爆料",
      "hint": "机模、配色、影像、屏幕、电池和芯片线索先看。",
      "items": [
        {
          "id": "weibo-a8094fd95942",
          "title": "数码闲聊站：iPhone 18 Pro系列W39累计销量176W，根据国庆期间的走势，W4…",
          "originalTitle": "",
          "source": "数码闲聊站",
          "brand": "iPhone",
          "type": "爆料",
          "trust": "高关注爆料源",
          "date": "2026-10-04",
          "time": "04:18",
          "publishedAt": "2026-10-04T04:18:00.000Z",
          "url": "https://weibo.com/6048569942/Rl5Mj9mAC",
          "image": "",
          "verdict": "先看",
          "takeaway": "iPhone 18 Pro系列W39累计销量176W，根据国庆期间的走势，W40预估累计销量250W+，两款机型均轻松完成单品激活100W++ [微风][微风][微风]",
          "detail": "iPhone 18 Pro系列W39累计销量176W，根据国庆期间的走势，W40预估累计销量250W+，两款机型均轻松完成单品激活100W++ [微风][微风][微风]",
          "keyPoints": [
            "爆料来源"
          ],
          "confidence": "来自常见高关注爆料源，适合重点看，但仍需等第二来源或发布会确认。",
          "impact": "这是提前爆料，能决定你要不要继续等某款机型，但还要交叉验证。",
          "action": "先收藏到重点爆料；等第二个可靠来源、认证或发布会再确认。"
        },
        {
          "id": "auto-61fed5a84012",
          "title": "iPhone 影像能力相关消息",
          "originalTitle": "",
          "source": "Gizmochina",
          "brand": "iPhone",
          "type": "爆料",
          "trust": "媒体汇总",
          "date": "2026-10-05",
          "time": "05:33",
          "publishedAt": "2026-10-05T05:33:08.000Z",
          "url": "https://www.gizmochina.com/2026/10/05/fitbit-edge-leaks-in-photos-as-googles-screen-equipped-tracker-that-works-with-iphone/",
          "image": "https://www.gizmochina.com/wp-content/uploads/2026/10/Google-Fitbit-Edge-Leak-300x200.jpg?x96852",
          "verdict": "先看",
          "takeaway": "iPhone 影像能力相关宣传或案例，主要看是否透露拍摄能力变化。",
          "detail": "iPhone 影像能力相关消息。重点看影像功能是否和新机硬件有关，如果只是拍摄案例或营销内容，参考价值会低一些。",
          "keyPoints": [
            "影像硬件",
            "屏幕形态",
            "爆料来源"
          ],
          "confidence": "媒体汇总或普通传闻，适合先收藏观察，不当作最终参数。",
          "impact": "这是提前爆料，能决定你要不要继续等某款机型，但还要交叉验证。",
          "action": "先收藏到重点爆料；等第二个可靠来源、认证或发布会再确认。"
        },
        {
          "id": "newsnow-d09c7a77bd47",
          "title": "比起折痕， iPhone Duo 的交互设计更加令人着迷",
          "originalTitle": "",
          "source": "少数派热榜",
          "brand": "iPhone",
          "type": "评测",
          "trust": "媒体汇总",
          "date": "2026-10-05",
          "time": "",
          "publishedAt": "",
          "url": "https://sspai.com/post/114972",
          "image": "",
          "verdict": "先看",
          "takeaway": "比起折痕， iPhone Duo 的交互设计更加令人着迷",
          "detail": "比起折痕， iPhone Duo 的交互设计更加令人着迷",
          "keyPoints": [
            "屏幕形态"
          ],
          "confidence": "媒体汇总或普通传闻，适合先收藏观察，不当作最终参数。",
          "impact": "这是提前爆料，能决定你要不要继续等某款机型，但还要交叉验证。",
          "action": "先收藏到重点爆料；等第二个可靠来源、认证或发布会再确认。"
        },
        {
          "id": "auto-076258f973c3",
          "title": "十年前的「外挂相机」，如何在华为 Mate 90 上复活？｜硬哲学",
          "originalTitle": "",
          "source": "爱范儿",
          "brand": "Huawei",
          "type": "评测",
          "trust": "媒体汇总",
          "date": "2026-10-04",
          "time": "14:49",
          "publishedAt": "2026-10-04T14:49:07.000Z",
          "url": "https://www.ifanr.com/1682933?utm_source=rss&utm_medium=rss&utm_campaign=",
          "image": "https://s3.ifanr.com/wp-content/uploads/2026/10/lark2pad-1791125067950-2.png",
          "verdict": "先看",
          "takeaway": "那个曾经太早出现的想法，这一次，可能终于等到了属于它的时代",
          "detail": "那个曾经太早出现的想法，这一次，可能终于等到了属于它的时代",
          "keyPoints": [
            "影像硬件"
          ],
          "confidence": "媒体汇总或普通传闻，适合先收藏观察，不当作最终参数。",
          "impact": "这是提前爆料，能决定你要不要继续等某款机型，但还要交叉验证。",
          "action": "先收藏到重点爆料；等第二个可靠来源、认证或发布会再确认。"
        },
        {
          "id": "weibo-f7e4d6168a26",
          "title": "数码闲聊站：华为Mate90系列明天发布，猜猜价格吧： 补充一些信息，Mate90是660…",
          "originalTitle": "",
          "source": "数码闲聊站",
          "brand": "Huawei",
          "type": "爆料",
          "trust": "高关注爆料源",
          "date": "2026-10-05",
          "time": "09:02",
          "publishedAt": "2026-10-05T09:02:13.476Z",
          "url": "https://weibo.com/6048569942/Rkw3lCtbI",
          "image": "https://tvax1.sinaimg.cn/mw2000/006BlblIgy1ihltiohha9j30zc3s9npd.jpg",
          "verdict": "先看",
          "takeaway": "华为Mate90系列明天发布，猜猜价格吧： 补充一些信息，Mate90是6600mAh电池+66W(100W)快充，50Mp可变光圈高动态大底主摄，50Mp聚光长焦，麒麟9030； Mate90 Pro是双层OLED，最高12000nits，麒麟9035，50Mp潜望镜支持5cm长焦微距； Mate90 PM/RS都是18EV 50Mp超大底主摄+40Mp…",
          "detail": "华为Mate90系列明天发布，猜猜价格吧： 补充一些信息，Mate90是6600mAh电池+66W(100W)快充，50Mp可变光圈高动态大底主摄，50Mp聚光长焦，麒麟9030； Mate90 Pro是双层OLED，最高12000nits，麒麟9035，50Mp潜望镜支持5cm长焦微距； Mate90 PM/RS都是18EV 50Mp超大底主摄+40Mp…",
          "keyPoints": [
            "影像硬件",
            "屏幕形态",
            "电池 / 充电",
            "成本 / 价格"
          ],
          "confidence": "来自常见高关注爆料源，适合重点看，但仍需等第二来源或发布会确认。",
          "impact": "这是提前爆料，能决定你要不要继续等某款机型，但还要交叉验证。",
          "action": "先收藏到重点爆料；等第二个可靠来源、认证或发布会再确认。"
        },
        {
          "id": "weibo-e4a68fd30029",
          "title": "数码闲聊站：摸了一下昨天 iQOO16 首销数据，竟然是近期已发安卓旗舰中的单品销量TOP…",
          "originalTitle": "",
          "source": "数码闲聊站",
          "brand": "vivo",
          "type": "爆料",
          "trust": "高关注爆料源",
          "date": "2026-10-05",
          "time": "09:02",
          "publishedAt": "2026-10-05T09:02:13.476Z",
          "url": "https://weibo.com/6048569942/RkuQYC8En",
          "image": "",
          "verdict": "先看",
          "takeaway": "摸了一下昨天 iQOO16 首销数据，竟然是近期已发安卓旗舰中的单品销量TOP1。 目前在狗猫抖三大电商平台的总销量是下半年安卓旗舰首销TOP1，而且是一杯打其它所有厂商的多杯组合，还几乎全打赢了……[哆啦A梦害怕]",
          "detail": "摸了一下昨天 iQOO16 首销数据，竟然是近期已发安卓旗舰中的单品销量TOP1。 目前在狗猫抖三大电商平台的总销量是下半年安卓旗舰首销TOP1，而且是一杯打其它所有厂商的多杯组合，还几乎全打赢了……[哆啦A梦害怕]",
          "keyPoints": [
            "爆料来源"
          ],
          "confidence": "来自常见高关注爆料源，适合重点看，但仍需等第二来源或发布会确认。",
          "impact": "这是提前爆料，能决定你要不要继续等某款机型，但还要交叉验证。",
          "action": "先收藏到重点爆料；等第二个可靠来源、认证或发布会再确认。"
        },
        {
          "id": "weibo-41b18bf8cfc0",
          "title": "数码闲聊站：耀子年底还有一堆新机，荣耀700 Pro系列有原生背屏，主打2亿超清影像。中端…",
          "originalTitle": "",
          "source": "数码闲聊站",
          "brand": "HONOR",
          "type": "爆料",
          "trust": "高关注爆料源",
          "date": "2026-10-05",
          "time": "09:02",
          "publishedAt": "2026-10-05T09:02:13.476Z",
          "url": "https://weibo.com/6048569942/RkuyMxv05",
          "image": "",
          "verdict": "先看",
          "takeaway": "耀子年底还有一堆新机，荣耀700 Pro系列有原生背屏，主打2亿超清影像。中端线还有X新品，7英寸大屏+超万级大电池，阔折叠加速中，阔直板也立项了，支持卷起来[二哈]",
          "detail": "耀子年底还有一堆新机，荣耀700 Pro系列有原生背屏，主打2亿超清影像。中端线还有X新品，7英寸大屏+超万级大电池，阔折叠加速中，阔直板也立项了，支持卷起来[二哈]",
          "keyPoints": [
            "影像硬件",
            "电池 / 充电",
            "爆料来源"
          ],
          "confidence": "来自常见高关注爆料源，适合重点看，但仍需等第二来源或发布会确认。",
          "impact": "这是提前爆料，能决定你要不要继续等某款机型，但还要交叉验证。",
          "action": "先收藏到重点爆料；等第二个可靠来源、认证或发布会再确认。"
        },
        {
          "id": "auto-9ea89cb4215d",
          "title": "2027 款玛莎拉蒂 Mcpura 车型上市：提供硬顶 / 敞篷双版本，237 万元起",
          "originalTitle": "",
          "source": "IT之家",
          "brand": "行业",
          "type": "爆料",
          "trust": "媒体汇总",
          "date": "2026-10-05",
          "time": "08:45",
          "publishedAt": "2026-10-05T08:45:57.000Z",
          "url": "https://www.ithome.com/1/009/843.htm",
          "image": "https://img.ithome.com/newsuploadfiles/2026/10/c6a23f68-f69e-4eca-8cdf-25eae3263367.png?x-bce-process=image/format,f_auto",
          "verdict": "先看",
          "takeaway": "IT之家 10 月 5 日消息，玛莎拉蒂宣布旗下 2027 款 Mcpura 车型正式上市，共推出硬顶版（Coupe）和敞篷版（Cielo）两款车型，售价分别为 237 万元和 270 万元。 该车提供神秘灰、隐秘灰、纯粹黑、冰川皓白、无界曜蓝、烈焰红、绝尘黄、皇家绿、灵动黑、魔力橙配色。前脸采用了与 GT2 赛车相同的设计语言，整个单体壳由碳纤维和复合材…",
          "detail": "IT之家 10 月 5 日消息，玛莎拉蒂宣布旗下 2027 款 Mcpura 车型正式上市，共推出硬顶版（Coupe）和敞篷版（Cielo）两款车型，售价分别为 237 万元和 270 万元。 该车提供神秘灰、隐秘灰、纯粹黑、冰川皓白、无界曜蓝、烈焰红、绝尘黄、皇家绿、灵动黑、魔力橙配色。前脸采用了与 GT2 赛车相同的设计语言，整个单体壳由碳纤维和复合材…",
          "keyPoints": [
            "外观 / 配色 / 尺寸",
            "成本 / 价格"
          ],
          "confidence": "媒体汇总或普通传闻，适合先收藏观察，不当作最终参数。",
          "impact": "这是提前爆料，能决定你要不要继续等某款机型，但还要交叉验证。",
          "action": "先收藏到重点爆料；等第二个可靠来源、认证或发布会再确认。"
        }
      ]
    },
    {
      "id": "iphone",
      "title": "iPhone 重点",
      "hint": "不是硬件爆料，但和 iPhone 体验或路线有关。",
      "items": [
        {
          "id": "auto-f88c473bc838",
          "title": "iPhone 相关消息",
          "originalTitle": "",
          "source": "Apple Newsroom",
          "brand": "iPhone",
          "type": "官方",
          "trust": "官方确认",
          "date": "2026-10-05",
          "time": "",
          "publishedAt": "",
          "url": "https://www.apple.com/newsroom/2026/09/celebrating-what-holds-us-on-iphone-18-pro/",
          "image": "",
          "verdict": "先看",
          "takeaway": "iPhone 相关消息。已转成中文摘要展示，详细内容可打开原文核对。",
          "detail": "iPhone 相关消息。这条来自英文来源，已先转成中文结论；需要更细节时再打开原文核对。",
          "keyPoints": [
            "影像硬件"
          ],
          "confidence": "官方内容，可直接作为已确认信息记录。",
          "impact": "影响拍照体验，买旗舰机时值得关注。",
          "action": "有具体参数就记录到参数库；没有参数就先收藏。"
        },
        {
          "id": "auto-07e6d6658c80",
          "title": "iPhone 18 Pro 发布 / 上市相关消息",
          "originalTitle": "",
          "source": "Apple Newsroom",
          "brand": "iPhone",
          "type": "官方",
          "trust": "官方确认",
          "date": "2026-10-05",
          "time": "",
          "publishedAt": "",
          "url": "https://www.apple.com/newsroom/2026/09/apple-debuts-iphone-18-pro-and-iphone-18-pro-max/",
          "image": "",
          "verdict": "先看",
          "takeaway": "iPhone 18 Pro 发布 / 上市相关消息。已转成中文摘要展示，详细内容可打开原文核对。",
          "detail": "iPhone 18 Pro 发布 / 上市相关消息。这条来自英文来源，已先转成中文结论；需要更细节时再打开原文核对。",
          "keyPoints": [
            "影像硬件",
            "电池 / 充电"
          ],
          "confidence": "官方内容，可直接作为已确认信息记录。",
          "impact": "影响日常体验，尤其是游戏、拍照和长时间使用。",
          "action": "有具体参数就记录到参数库；没有参数就先收藏。"
        },
        {
          "id": "auto-a2ac39257e4d",
          "title": "方方面面都熟悉，方方面面都更好：iPhone 18 Pro 体验",
          "originalTitle": "",
          "source": "少数派",
          "brand": "iPhone",
          "type": "评测",
          "trust": "媒体汇总",
          "date": "2026-10-04",
          "time": "07:58",
          "publishedAt": "2026-10-04T07:58:39.000Z",
          "url": "https://sspai.com/post/115308",
          "image": "",
          "verdict": "先看",
          "takeaway": "iPhone 18 Pro 也许不会让你感觉焕然一新，却在许多地方都变得更加完整了。",
          "detail": "iPhone 18 Pro 也许不会让你感觉焕然一新，却在许多地方都变得更加完整了。",
          "keyPoints": [
            "评测"
          ],
          "confidence": "媒体汇总或普通传闻，适合先收藏观察，不当作最终参数。",
          "impact": "这是实际体验内容，买前适合重点看缺点和取舍。",
          "action": "中文源可以直接点开快读；看完只保留和购机有关的点。"
        },
        {
          "id": "newsnow-3cd4bd7d436d",
          "title": "刚看到iPhone18pro系列的销量信息，卖的太好了，感觉好心酸，今年这波集体涨价潮，一下子让安卓性价比低了很多，不涨又不行，结果就是让更多的人跑去买iPhone，其实也很好理解，价格相差能接受的情况下，选iPhone还是其他，相信绝大部分人的答案还是iPhone。",
          "originalTitle": "",
          "source": "酷安热榜",
          "brand": "iPhone",
          "type": "爆料",
          "trust": "高关注爆料源",
          "date": "2026-10-05",
          "time": "",
          "publishedAt": "",
          "url": "https://www.coolapk.com/feed/74162856",
          "image": "",
          "verdict": "先看",
          "takeaway": "刚看到iPhone18pro系列的销量信息，卖的太好了，感觉好心酸，今年这波集体涨价潮，一下子让安卓性价比低了很多，不涨又不行，结果就是让更多的人跑去买iPhone，其实也很好理解，价格相差能接受的情况下，选iPhone还是其他，相信绝大部分人的答案还是iPhone。",
          "detail": "刚看到iPhone18pro系列的销量信息，卖的太好了，感觉好心酸，今年这波集体涨价潮，一下子让安卓性价比低了很多，不涨又不行，结果就是让更多的人跑去买iPhone，其实也很好理解，价格相差能接受的情况下，选iPhone还是其他，相信绝大部分人的答案还是iPhone。",
          "keyPoints": [
            "成本 / 价格"
          ],
          "confidence": "媒体汇总或普通传闻，适合先收藏观察，不当作最终参数。",
          "impact": "影响购买预算，值得先看。",
          "action": "有具体参数就记录到参数库；没有参数就先收藏。"
        },
        {
          "id": "newsnow-bbceddc2e5fd",
          "title": "iPhone 18 Pro系列W39国内销量曝光：累计约176万台",
          "originalTitle": "",
          "source": "酷安热榜",
          "brand": "iPhone",
          "type": "爆料",
          "trust": "高关注爆料源",
          "date": "2026-10-05",
          "time": "",
          "publishedAt": "",
          "url": "https://www.coolapk.com/feed/74157969",
          "image": "",
          "verdict": "先看",
          "takeaway": "iPhone 18 Pro系列W39国内销量曝光：累计约176万台",
          "detail": "iPhone 18 Pro系列W39国内销量曝光：累计约176万台",
          "keyPoints": [
            "爆料"
          ],
          "confidence": "媒体汇总或普通传闻，适合先收藏观察，不当作最终参数。",
          "impact": "当作提前信号，别急着下结论，等第二个来源验证。",
          "action": "英文源先别打开，除非你要我帮你翻译/判断。"
        },
        {
          "id": "auto-728bbee10ddb",
          "title": "iPhone 发布 / 上市相关消息",
          "originalTitle": "",
          "source": "Apple Newsroom",
          "brand": "iPhone",
          "type": "官方",
          "trust": "官方确认",
          "date": "2026-10-05",
          "time": "",
          "publishedAt": "",
          "url": "https://www.apple.com/newsroom/2026/09/apple-unveils-iphone-duo/",
          "image": "",
          "verdict": "先看",
          "takeaway": "iPhone 有发布或新功能消息，适合确认是否和新机有关。",
          "detail": "iPhone 发布 / 上市相关消息。这条来自英文来源，已先转成中文结论；需要更细节时再打开原文核对。",
          "keyPoints": [
            "官方"
          ],
          "confidence": "官方内容，可直接作为已确认信息记录。",
          "impact": "可信度高，但如果不是配置/价格消息，只需要扫一眼。",
          "action": "英文源先别打开，除非你要我帮你翻译/判断。"
        }
      ]
    },
    {
      "id": "market",
      "title": "行业趋势",
      "hint": "看方向，不急着当购买依据。",
      "items": [
        {
          "id": "auto-6c3b914e07a2",
          "title": "iPhone 18 Pro 对比 Galaxy S26 Ultra：差异整理",
          "originalTitle": "",
          "source": "Gizmochina",
          "brand": "Samsung",
          "type": "爆料",
          "trust": "媒体汇总",
          "date": "2026-10-05",
          "time": "07:28",
          "publishedAt": "2026-10-05T07:28:03.000Z",
          "url": "https://www.gizmochina.com/2026/10/05/iphone-18-pro-vs-galaxy-s26-ultra/",
          "image": "https://www.gizmochina.com/wp-content/uploads/2026/10/image-7-300x161.png?x96852",
          "verdict": "扫一眼",
          "takeaway": "iPhone 18 Pro 对比 Galaxy S26 Ultra：重点看定位、配置差异和价格差，判断是否值得等更高端型号。",
          "detail": "iPhone 18 Pro 对比 Galaxy S26 Ultra 的差异整理。重点看两款机型的定位、影像规格、屏幕尺寸、价格区间和发布时间是否拉开差距。",
          "keyPoints": [
            "影像硬件",
            "电池 / 充电",
            "成本 / 价格"
          ],
          "confidence": "媒体汇总或普通传闻，适合先收藏观察，不当作最终参数。",
          "impact": "影响购买预算，值得先看。",
          "action": "有具体参数就记录到参数库；没有参数就先收藏。"
        },
        {
          "id": "auto-cf5b402ad822",
          "title": "iPhone 18 Pro 对比 Xiaomi 18 Pro：差异整理",
          "originalTitle": "",
          "source": "Gizmochina",
          "brand": "Xiaomi",
          "type": "爆料",
          "trust": "媒体汇总",
          "date": "2026-10-05",
          "time": "05:33",
          "publishedAt": "2026-10-05T05:33:33.000Z",
          "url": "https://www.gizmochina.com/2026/10/05/iphone-18-pro-vs-xiaomi-18-pro/",
          "image": "https://www.gizmochina.com/wp-content/uploads/2026/10/image-6-300x165.png?x96852",
          "verdict": "扫一眼",
          "takeaway": "iPhone 18 Pro 对比 Xiaomi 18 Pro：重点看定位、配置差异和价格差，判断是否值得等更高端型号。",
          "detail": "iPhone 18 Pro 对比 Xiaomi 18 Pro 的差异整理。重点看两款机型的定位、影像规格、屏幕尺寸、价格区间和发布时间是否拉开差距。",
          "keyPoints": [
            "影像硬件"
          ],
          "confidence": "媒体汇总或普通传闻，适合先收藏观察，不当作最终参数。",
          "impact": "影响拍照体验，买旗舰机时值得关注。",
          "action": "有具体参数就记录到参数库；没有参数就先收藏。"
        },
        {
          "id": "newsnow-2c609e9926d7",
          "title": "能不能官方投诉线下门店的，送的礼盒拿个 pdd 手机壳放进去给我。气炸了。",
          "originalTitle": "",
          "source": "酷安热榜",
          "brand": "行业",
          "type": "爆料",
          "trust": "高关注爆料源",
          "date": "2026-10-05",
          "time": "",
          "publishedAt": "",
          "url": "https://www.coolapk.com/feed/74163561",
          "image": "",
          "verdict": "扫一眼",
          "takeaway": "能不能官方投诉线下门店的，送的礼盒拿个 pdd 手机壳放进去给我。气炸了。",
          "detail": "能不能官方投诉线下门店的，送的礼盒拿个 pdd 手机壳放进去给我。气炸了。",
          "keyPoints": [
            "爆料"
          ],
          "confidence": "媒体汇总或普通传闻，适合先收藏观察，不当作最终参数。",
          "impact": "当作提前信号，别急着下结论，等第二个来源验证。",
          "action": "英文源先别打开，除非你要我帮你翻译/判断。"
        },
        {
          "id": "newsnow-e6769502c052",
          "title": "刚才打电话问保值换新到货情况，销售原话“RS太麻烦了，大家都不想卖”，接电话的小伙子对我一顿冷嘲热讽，我说等会我去你们门店找你们店长，他说我们店长这几天不上班你来了也白来，我已经气炸了我把通话录音反馈给华为客服了，也打电话投诉了，我等会去门店要他的工号把录音给他店长听，连门店一块投诉了[发怒]。#鸿蒙7# #华为Mate90ProMax# #荣耀Magic9ProMax#",
          "originalTitle": "",
          "source": "酷安热榜",
          "brand": "HONOR",
          "type": "爆料",
          "trust": "高关注爆料源",
          "date": "2026-10-05",
          "time": "",
          "publishedAt": "",
          "url": "https://www.coolapk.com/feed/74155821",
          "image": "",
          "verdict": "扫一眼",
          "takeaway": "刚才打电话问保值换新到货情况，销售原话“RS太麻烦了，大家都不想卖”，接电话的小伙子对我一顿冷嘲热讽，我说等会我去你们门店找你们店长，他说我们店长这几天不上班你来了也白来，我已经气炸了我把通话录音反馈给华为客服了，也打电话投诉了，我等会去门店要他的工号把录音给他店长听，连门店一块投诉了[发怒]。#鸿蒙7# #华为Mate90ProMax# #荣耀Magic…",
          "detail": "刚才打电话问保值换新到货情况，销售原话“RS太麻烦了，大家都不想卖”，接电话的小伙子对我一顿冷嘲热讽，我说等会我去你们门店找你们店长，他说我们店长这几天不上班你来了也白来，我已经气炸了我把通话录音反馈给华为客服了，也打电话投诉了，我等会去门店要他的工号把录音给他店长听，连门店一块投诉了[发怒]。#鸿蒙7# #华为Mate90ProMax# #荣耀Magic…",
          "keyPoints": [
            "爆料"
          ],
          "confidence": "媒体汇总或普通传闻，适合先收藏观察，不当作最终参数。",
          "impact": "当作提前信号，别急着下结论，等第二个来源验证。",
          "action": "英文源先别打开，除非你要我帮你翻译/判断。"
        },
        {
          "id": "coolapk-user-5dd961bfdc75",
          "title": "竹本青：iQOO16首销情况曝光：同期约为上代的50%",
          "originalTitle": "",
          "source": "竹本青",
          "brand": "vivo",
          "type": "爆料",
          "trust": "高可信爆料",
          "date": "2026-10-05",
          "time": "04:47",
          "publishedAt": "2026-10-05T04:47:58.000Z",
          "url": "https://www.coolapk.com/feed/74172647",
          "image": "http://image.coolapk.com/feed/2026/1005/12/4248714_c7b26675_5677_2421_188@1440x1025.jpg",
          "verdict": "扫一眼",
          "takeaway": "【iQOO 16 首销情况曝光：同期约为上代的50%，上上代的100%】 10月5日，博主「RD观测」披露第三方统计的iQOO 16首销情况。以首销当天（20:30开售）+后三天为标准，该机市场表现如下： ● 上代iQOO 15 的50% ● 上上代iQOO 13 的100% 博主补充称，如果不出意外，后面所有机型的首销期数据都按照首销当日+后三天统计，且…",
          "detail": "【iQOO 16 首销情况曝光：同期约为上代的50%，上上代的100%】 10月5日，博主「RD观测」披露第三方统计的iQOO 16首销情况。以首销当天（20:30开售）+后三天为标准，该机市场表现如下： ● 上代iQOO 15 的50% ● 上上代iQOO 13 的100% 博主补充称，如果不出意外，后面所有机型的首销期数据都按照首销当日+后三天统计，且…",
          "keyPoints": [
            "爆料"
          ],
          "confidence": "可信度较高，但仍属于发布前线索。",
          "impact": "当作提前信号，别急着下结论，等第二个来源验证。",
          "action": "英文源先别打开，除非你要我帮你翻译/判断。"
        },
        {
          "id": "auto-53941eccad30",
          "title": "Xiaomi 18 Pro Max 对比 Honor Magic9 Pro Max：差异整理",
          "originalTitle": "",
          "source": "Gizmochina",
          "brand": "HONOR",
          "type": "爆料",
          "trust": "媒体汇总",
          "date": "2026-10-05",
          "time": "08:40",
          "publishedAt": "2026-10-05T08:40:25.000Z",
          "url": "https://www.gizmochina.com/2026/10/05/xiaomi-18-pro-max-vs-honor-magic9-pro-max/",
          "image": "https://www.gizmochina.com/wp-content/uploads/2026/10/image-9-300x167.png?x96852",
          "verdict": "可略过",
          "takeaway": "Xiaomi 18 Pro Max 对比 Honor Magic9 Pro Max：重点看定位、配置差异和价格差，判断是否值得等更高端型号。",
          "detail": "Xiaomi 18 Pro Max 对比 Honor Magic9 Pro Max 的差异整理。重点看两款机型的定位、影像规格、屏幕尺寸、价格区间和发布时间是否拉开差距。",
          "keyPoints": [
            "影像硬件",
            "成本 / 价格"
          ],
          "confidence": "媒体汇总或普通传闻，适合先收藏观察，不当作最终参数。",
          "impact": "影响购买预算，值得先看。",
          "action": "有具体参数就记录到参数库；没有参数就先收藏。"
        }
      ]
    }
  ]
};
