window.phoneRadarDaily = {
  "updatedAt": "2026-07-21T03:43:44.808Z",
  "issueDate": "2026-07-21",
  "issue": "VOL.260721",
  "title": "手机情报日报",
  "intro": "今日筛出 8 条重点，其中 8 条是重点爆料，包含 3 条 iPhone 相关、0 条官方确认、0 条参数线索。",
  "stats": {
    "total": 8,
    "iphone": 3,
    "leaks": 8,
    "official": 0,
    "specs": 0
  },
  "sections": [
    {
      "id": "leaks",
      "title": "重点爆料",
      "hint": "机模、配色、影像、屏幕、电池和芯片线索先看。",
      "items": [
        {
          "id": "auto-c85e6695758d",
          "title": "消息称苹果打样 7 英寸超大屏，有概率用于 iPhone 20 Pro Max",
          "originalTitle": "",
          "source": "IT之家",
          "brand": "iPhone",
          "type": "爆料",
          "trust": "媒体汇总",
          "date": "2026-07-21",
          "time": "02:51",
          "publishedAt": "2026-07-21T02:51:53.000Z",
          "url": "https://www.ithome.com/0/979/386.htm",
          "image": "https://img.ithome.com/newsuploadfiles/2026/7/628f41af-73db-422c-876e-6d30127dc727.jpg",
          "verdict": "先看",
          "takeaway": "IT之家 7 月 21 日消息，博主 @数码闲聊站 今日爆料，苹果正在打样一块超大屏，物理尺寸 6.96 英寸 ±，标准尺寸是 7 英寸 ±， 有概率运用于 iPhone 20 Pro Max？ 有待进一步确定。 博主还称，新屏幕的比例和现在的 6.9 英寸差不多，适人握持。 作为参考，最新的 iPhone 17 Pro Max 屏幕尺寸为 6.9 英寸，…",
          "detail": "IT之家 7 月 21 日消息，博主 @数码闲聊站 今日爆料，苹果正在打样一块超大屏，物理尺寸 6.96 英寸 ±，标准尺寸是 7 英寸 ±， 有概率运用于 iPhone 20 Pro Max？ 有待进一步确定。 博主还称，新屏幕的比例和现在的 6.9 英寸差不多，适人握持。 作为参考，最新的 iPhone 17 Pro Max 屏幕尺寸为 6.9 英寸，…",
          "keyPoints": [
            "外观 / 配色 / 尺寸",
            "屏幕形态",
            "爆料来源"
          ],
          "confidence": "来自常见高关注爆料源，适合重点看，但仍需等第二来源或发布会确认。",
          "impact": "这是提前爆料，能决定你要不要继续等某款机型，但还要交叉验证。",
          "action": "先收藏到重点爆料；等第二个可靠来源、认证或发布会再确认。"
        },
        {
          "id": "weibo-86e5e436880e",
          "title": "数码闲聊站：一条独家超前瞻信息，苹果正在打样一块超大屏，物理尺寸6.96英寸±，标准尺寸是…",
          "originalTitle": "",
          "source": "数码闲聊站",
          "brand": "iPhone",
          "type": "爆料",
          "trust": "高关注爆料源",
          "date": "2026-07-21",
          "time": "02:38",
          "publishedAt": "2026-07-21T02:38:00.000Z",
          "url": "https://weibo.com/6048569942/R9G4trdtx",
          "image": "",
          "verdict": "先看",
          "takeaway": "一条独家超前瞻信息，苹果正在打样一块超大屏，物理尺寸6.96英寸±，标准尺寸是7英寸±，有概率运用于iPhone 20 Pro Max？有待进一步确定",
          "detail": "一条独家超前瞻信息，苹果正在打样一块超大屏，物理尺寸6.96英寸±，标准尺寸是7英寸±，有概率运用于iPhone 20 Pro Max？有待进一步确定",
          "keyPoints": [
            "外观 / 配色 / 尺寸",
            "爆料来源"
          ],
          "confidence": "来自常见高关注爆料源，适合重点看，但仍需等第二来源或发布会确认。",
          "impact": "这是提前爆料，能决定你要不要继续等某款机型，但还要交叉验证。",
          "action": "先收藏到重点爆料；等第二个可靠来源、认证或发布会再确认。"
        },
        {
          "id": "auto-6797fefe2496",
          "title": "iPhone 18 Pro 芯片 / 性能相关消息",
          "originalTitle": "",
          "source": "9to5Mac",
          "brand": "iPhone",
          "type": "爆料",
          "trust": "媒体汇总",
          "date": "2026-07-20",
          "time": "20:34",
          "publishedAt": "2026-07-20T20:34:11.000Z",
          "url": "https://9to5mac.com/2026/07/20/iphone-18-pros-new-a20-chip-rumored-to-bring-two-major-upgrades/",
          "image": "https://9to5mac.com/wp-content/uploads/sites/6/2026/01/iphone-18-mockup-red.jpg?quality=82&strip=all&w=1600",
          "verdict": "先看",
          "takeaway": "iPhone 芯片或连接能力相关线索，可能影响性能和续航判断。",
          "detail": "iPhone 18 Pro 芯片 / 性能相关消息。这条来自英文来源，已先转成中文结论；需要更细节时再打开原文核对。",
          "keyPoints": [
            "芯片 / 性能",
            "爆料来源"
          ],
          "confidence": "媒体汇总或普通传闻，适合先收藏观察，不当作最终参数。",
          "impact": "这是提前爆料，能决定你要不要继续等某款机型，但还要交叉验证。",
          "action": "先收藏到重点爆料；等第二个可靠来源、认证或发布会再确认。"
        },
        {
          "id": "auto-ab347374b17a",
          "title": "三星 Galaxy Z Fold8 阔折叠手机渲染图再曝：Flex Titanium 折叠方案",
          "originalTitle": "",
          "source": "IT之家",
          "brand": "Samsung",
          "type": "爆料",
          "trust": "媒体汇总",
          "date": "2026-07-21",
          "time": "02:16",
          "publishedAt": "2026-07-21T02:16:21.000Z",
          "url": "https://www.ithome.com/0/979/333.htm",
          "image": "https://img.ithome.com/newsuploadfiles/2026/7/a56e435d-881a-45f7-a180-c1f3f1d2c66d.jpg",
          "verdict": "先看",
          "takeaway": "IT之家 7 月 21 日消息，消息源 Roland Quandt 昨日（7 月 20 日）在 Bluesky 平台发布动态， 分享了三星 Galaxy Z Fold8 阔折叠手机新渲染图。 颜色方面，本次曝光的渲染图展示了石墨灰（Graphite）、奶油色（Cream）和薰衣草色（Lavender）三种颜色，此前消息称三星还将会推出“开心果绿”（Pist…",
          "detail": "IT之家 7 月 21 日消息，消息源 Roland Quandt 昨日（7 月 20 日）在 Bluesky 平台发布动态， 分享了三星 Galaxy Z Fold8 阔折叠手机新渲染图。 颜色方面，本次曝光的渲染图展示了石墨灰（Graphite）、奶油色（Cream）和薰衣草色（Lavender）三种颜色，此前消息称三星还将会推出“开心果绿”（Pist…",
          "keyPoints": [
            "外观 / 配色 / 尺寸",
            "爆料来源"
          ],
          "confidence": "媒体汇总或普通传闻，适合先收藏观察，不当作最终参数。",
          "impact": "这是提前爆料，能决定你要不要继续等某款机型，但还要交叉验证。",
          "action": "先收藏到重点爆料；等第二个可靠来源、认证或发布会再确认。"
        },
        {
          "id": "auto-e371307044b5",
          "title": "消息称小米手机今年出货目标由 9000 万部上调至 1.1 亿部，内部认为存储行情有望反转",
          "originalTitle": "",
          "source": "IT之家",
          "brand": "Xiaomi",
          "type": "爆料",
          "trust": "媒体汇总",
          "date": "2026-07-21",
          "time": "02:02",
          "publishedAt": "2026-07-21T02:02:53.000Z",
          "url": "https://www.ithome.com/0/979/328.htm",
          "image": "https://img.ithome.com/newsuploadfiles/2025/8/236b201a-e28a-4160-8029-d8a8e74b794f.jpg?x-bce-process=image/auto-orient,o_1",
          "verdict": "先看",
          "takeaway": "IT之家 7 月 21 日消息，界面新闻今天（21 日）援引供应链消息称，小米已将 2026 年全年智能手机出货目标从约 9000 万部上调至 1.1 亿部，增幅约 16%，上调的增量部分 主要来自低端机型 。 接近小米的人士透露，此次上调出货目标是小米内部认为 当前的存储行情有望迎来反转 。受上游存储芯片的成本持续上涨，小米在今年曾两次下调其出货目标。…",
          "detail": "IT之家 7 月 21 日消息，界面新闻今天（21 日）援引供应链消息称，小米已将 2026 年全年智能手机出货目标从约 9000 万部上调至 1.1 亿部，增幅约 16%，上调的增量部分 主要来自低端机型 。 接近小米的人士透露，此次上调出货目标是小米内部认为 当前的存储行情有望迎来反转 。受上游存储芯片的成本持续上涨，小米在今年曾两次下调其出货目标。…",
          "keyPoints": [
            "芯片 / 性能",
            "成本 / 价格",
            "爆料来源"
          ],
          "confidence": "媒体汇总或普通传闻，适合先收藏观察，不当作最终参数。",
          "impact": "这是提前爆料，能决定你要不要继续等某款机型，但还要交叉验证。",
          "action": "先收藏到重点爆料；等第二个可靠来源、认证或发布会再确认。"
        },
        {
          "id": "weibo-aee685a1dbc9",
          "title": "数码闲聊站：独家信息：子系迭代线T正常打磨中，2nm旗舰芯，目前工程机打磨SM8950(同…",
          "originalTitle": "",
          "source": "数码闲聊站",
          "brand": "Samsung",
          "type": "爆料",
          "trust": "高关注爆料源",
          "date": "2026-07-21",
          "time": "01:07",
          "publishedAt": "2026-07-21T01:07:50.000Z",
          "url": "https://weibo.com/6048569942/R9FtSqF2c",
          "image": "",
          "verdict": "先看",
          "takeaway": "独家信息，子系迭代线T正常打磨中，2nm旗舰芯，目前工程机打磨SM8950(同步备选DX6)，有内置大尺寸风扇，屏幕评估2K三星直屏👖",
          "detail": "独家信息，子系迭代线T正常打磨中，2nm旗舰芯，目前工程机打磨SM8950(同步备选DX6)，有内置大尺寸风扇，屏幕评估2K三星直屏👖",
          "keyPoints": [
            "外观 / 配色 / 尺寸",
            "屏幕形态",
            "爆料来源"
          ],
          "confidence": "来自常见高关注爆料源，适合重点看，但仍需等第二来源或发布会确认。",
          "impact": "这是提前爆料，能决定你要不要继续等某款机型，但还要交叉验证。",
          "action": "先收藏到重点爆料；等第二个可靠来源、认证或发布会再确认。"
        },
        {
          "id": "weibo-d234588a3879",
          "title": "数码闲聊站：耀子的机器人手机最近很火，摸了一下核心信息，感觉是目前手机精密制造的巅峰： 2…",
          "originalTitle": "",
          "source": "数码闲聊站",
          "brand": "HONOR",
          "type": "爆料",
          "trust": "高关注爆料源",
          "date": "2026-07-20",
          "time": "09:35",
          "publishedAt": "2026-07-20T09:35:55.000Z",
          "url": "https://weibo.com/6048569942/R9znCn7UV",
          "image": "",
          "verdict": "先看",
          "takeaway": "耀子的机器人手机最近很火，摸了一下核心信息，感觉是目前手机精密制造的巅峰： 200Mp云台影像是基础，核心机构件、电机、模组全部是荣耀自研和独立定制，整套云台及翻转机构新增了近100个零部件。 其中定制了4个电机，内部动力采用了特殊多极充磁工艺，直径最小的仅6mm。 核心结构件为了可靠性全部使用了钛合金材质，材料及加工成本比常规铝合金摆臂多3倍。并且装配流…",
          "detail": "耀子的机器人手机最近很火，摸了一下核心信息，感觉是目前手机精密制造的巅峰： 200Mp云台影像是基础，核心机构件、电机、模组全部是荣耀自研和独立定制，整套云台及翻转机构新增了近100个零部件。 其中定制了4个电机，内部动力采用了特殊多极充磁工艺，直径最小的仅6mm。 核心结构件为了可靠性全部使用了钛合金材质，材料及加工成本比常规铝合金摆臂多3倍。并且装配流…",
          "keyPoints": [
            "影像硬件",
            "成本 / 价格",
            "爆料来源"
          ],
          "confidence": "来自常见高关注爆料源，适合重点看，但仍需等第二来源或发布会确认。",
          "impact": "这是提前爆料，能决定你要不要继续等某款机型，但还要交叉验证。",
          "action": "先收藏到重点爆料；等第二个可靠来源、认证或发布会再确认。"
        },
        {
          "id": "weibo-3b3a2c6e241d",
          "title": "数码闲聊站：OPPO A7 Pro Max，绿系首个万级大电池： 6.78\"1.5K 12…",
          "originalTitle": "",
          "source": "数码闲聊站",
          "brand": "OPPO",
          "type": "爆料",
          "trust": "高关注爆料源",
          "date": "2026-07-20",
          "time": "06:13",
          "publishedAt": "2026-07-20T06:13:42.000Z",
          "url": "https://weibo.com/6048569942/R9y3x9Ss5",
          "image": "",
          "verdict": "先看",
          "takeaway": "OPPO A7 Pro Max，绿系首个万级大电池： 6.78\"1.5K 120Hz OLED直屏，骁龙4 Gen5处理器，10000mAh单电芯大电池，80W快充，前置50Mp，后置50Mp+2Mp，8.47mm/226g……[doge]",
          "detail": "OPPO A7 Pro Max，绿系首个万级大电池： 6.78\"1.5K 120Hz OLED直屏，骁龙4 Gen5处理器，10000mAh单电芯大电池，80W快充，前置50Mp，后置50Mp+2Mp，8.47mm/226g……[doge]",
          "keyPoints": [
            "屏幕形态",
            "电池 / 充电",
            "芯片 / 性能",
            "爆料来源"
          ],
          "confidence": "来自常见高关注爆料源，适合重点看，但仍需等第二来源或发布会确认。",
          "impact": "这是提前爆料，能决定你要不要继续等某款机型，但还要交叉验证。",
          "action": "先收藏到重点爆料；等第二个可靠来源、认证或发布会再确认。"
        }
      ]
    }
  ]
};
